"Time-stamp: <2021-02-19 17:40:19 anup>"
"insilico input file for astrocyte mglu_receptor_hill (mGluR1)"
"Ref: zou2017, conn1997, wisniewski2002, zhang2005, nieden2005, balazs1997"

dxdt : 0,
mglur_hill_ip3_cyt_flux : 0.0,

"parameters for glutamate"
mglur_hill_v_max_glu : 0.65e-06,	"ctrl(dhpg): 0.65e-06, AD(dhpg): 1.4e-06"
mglur_hill_k_diss_glu : 11.0e-06,	"ctrl(dhpg): 11e-06, AD(dhpg): 3.0e-06, glutamate: 11e-6, dhpg: 6e-6"
mglur_hill_coop_glu : 2, 
mglur_hill_ip3_cyt_flux_glu : 0.0,

"parameters for dhpg" 
mglur_hill_v_max_dhpg : 0.65e-06,	"ctrl(dhpg): 0.65e-06, AD(dhpg): 1.4e-06"
mglur_hill_k_diss_dhpg : 6.0e-06,	"ctrl(dhpg): 6.0e-06, AD(dhpg): 3.0e-06, glutamate: 11e-6, dhpg: 6e-6"
mglur_hill_coop_dhpg : 2,
mglur_hill_ip3_cyt_flux_dhpg : 0.0,